version: '3.1'

services:
  node:
    image: docker.pkg.github.com/hansanghyeon/meta-crawler/meta-crawler:1.0.4
    ports:
      - '8080'
    volumes:
      - ./static:/app/static
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
