version: '3.1'

services:
  node:
    container_name: meta-crawler-node
    image: docker.pkg.github.com/hansanghyeon/meta-crawler/meta-crawler:1.1.1
    ports:
      - '8080'
    environment:
      - DB_HOST=meta-crawler-mongodb
      - DB=admin
    volumes:
      - ./static:/app/static
    networks:
      - backend
  mongodb:
    container_name: meta-crawler-mongodb
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
    networks:
      - backend

networks:
  backend:
    driver: bridge
volumes:
  mongo:
